server:
    port: 4000

spring:
    main:
        web-application-type: servlet
        allow-bean-definition-overriding: true
    profiles:
        default: local
    
    application:
        name: AuthHub
    
    config:
        import:
            - security/application-db.yml
            - security/application-oauth2.yml
    
    servlet:
        multipart:
            max-file-size: 5MB
            max-request-size: 5MB